### ISSUE TITLE
Can I have detail instruction ?

### ISSUE THREAD

**Issue by heliosfx** [PoomSmart/ASUS-FX504GE-Hackintosh#1]
please give me a detail instruction. thanks alot.

**Comment by deg-jc** [comment]
I found another instruction based on this one. Take a look: 
https://github.com/MegaStood/Hackintosh-FX504GE-ES72

And specifically, wich part were u stucked on?

**Comment by PoomSmart** [comment]
> Detailed instruction

Nothing complicated, just like certain other laptops, use the provided files when in doubt.
