### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by felixyonathan** [PoomSmart/ASUS-FX504GE-Hackintosh#17]
I successfully booted into MacOS Catalina, but the keyboard is not working (TouchPad is also not working, but I've been using a wireless mouse anyway.).

Btw I did the step in **Add** _12. VoodooPS2Controller (PS/2 keyboard) (Must also be installed at /Library/Extensions)._

This is my EFI folder https://drive.google.com/drive/folders/18v6feNIeYcxmYZZRq8uN9NJzCUm-KSQJ?usp=sharing

Any suggestion? Thank you very much.

**Comment by 0tabek16** [comment]
Populate your `config.plist` file using `ProperTree`. It has an option called `OC Snapshot` on `File` menu.

**Comment by felixyonathan** [comment]
Did it. Please take a look.

**Comment by 0tabek16** [comment]
yes, that's correct. but please remove these kexts: `VoodooI2CHID`, `VoodooI2C`, `VoodooI2CServices`, `VoodooGPIO`

These kexts for touchpad. `VoodooI2C` causes `kernel panic` with `OpenCore`

**Comment by felixyonathan** [comment]
Thank you very much. It worked. I got a problem with adding a Windows boot entry though. I should open a new thread, right
