### ISSUE TITLE
I can't show the HHD

### ISSUE THREAD

**Issue by furthurr** [PoomSmart/ASUS-FX504GE-Hackintosh#2]
I can't see the HHD, :( i can install but when reboot i can not change to my HHD for the firts boot.
![00](https://user-images.githubusercontent.com/639790/58228138-42230800-7cf3-11e9-8126-6078aa95ad94.png)

**Comment by furthurr** [comment]
SOLVE ... my problem was the "config.plist"  ... I did create a new one :) and now can see the hhd :)

**Comment by PoomSmart** [comment]
config.plist is not supposed to be copied and pasted on the other machine without a careful modification. Be sure to compare the plists and copy over only the settings that solve your issues.
