### ISSUE TITLE
Help setting up Trackpad

### ISSUE THREAD

**Issue by RRC07** [PoomSmart/ASUS-FX504GE-Hackintosh#3]
Hello, I have been following your guide and was successfully able to set everything up except for the trackpad.
I have followed the GPIO pinning and replaced whatever needs to replaced using your instruction and still it doesn't work. I have attached my DSDT.
Thanks.
[Archive.zip](https://github.com/PoomSmart/ASUS-FX504GE-Hackintosh/files/3269306/Archive.zip)

**Comment by PoomSmart** [comment]
DSDT looks okay. It is possible that you have installed VoodooI2C kexts incorrectly. VoodooI2C version must be 2.2 or higher. There are also a few Clover I2C patches you need to have in config.plist

**Comment by RRC07** [comment]
Even I felt that the kexts were not loaded. I think I have added the I2C patches and the VoodooI2C version is the latest.
Here's my CLOVER folder for reference.

[CLOVER.zip](https://github.com/PoomSmart/ASUS-FX504GE-Hackintosh/files/3269711/CLOVER.zip)

**Comment by RRC07** [comment]
From the output of kextstat using terminal, I'm not able to find VoodooI2C.
[kextstat.txt](https://github.com/PoomSmart/ASUS-FX504GE-Hackintosh/files/3269716/kextstat.txt)

**Comment by PoomSmart** [comment]
1. Remove VoodooI2CUPDDEngine.kext from everywhere
2. How did you rebuilt kext caches step-by-step?

**Comment by RRC07** [comment]
I have removed the aforementioned kext. This is what I follow to rebuild kext caches.

1. Using Finder create a folder on your desktop and copy all the kexts you want to install into it.

2. Open Terminal and change the active path to the folder you created in step 1 using the "CD" command.

3. Install the Kexts into /Library/Extensions using the following command :-
Code: sudo cp -R *.kext /Library/Extensions

4. Then rebuild the caches using the following command :-
Code: sudo kextcache -i /

5. Once finished reboot your system.

**Comment by PoomSmart** [comment]
Between step 3 and 4, it's clear that you did not set the correct permissions for those kexts. You need to run the following commands:
- `sudo chmod -R 755 <your-kext>`
- `sudo chown -R 0:0 <your-kext>`
- `sudo touch <your-kext>`
