### ISSUE TITLE
我的笔记本是FX504GE：i7-8750H

### ISSUE THREAD

**Issue by wr-yt** [PoomSmart/ASUS-FX504GE-Hackintosh#5]
触摸板不能工作，麻烦打下指点下，

**Comment by PoomSmart** [comment]
Unless absolutely necessary, report in English. This issue will be ignored and locked otherwise.

**Comment by wr-yt** [comment]
My notebook is FX504GE: i7-8750H，The touchpad doesn't work, it's troublesome to lay down the finger

**Comment by wr-yt** [comment]
I only installed macos now, if you can hope to borrow the pudding of your touchpad, because our two notebook models are the same, but the cpu is not the same, I think it should be universal, thank you very much.

**Comment by PoomSmart** [comment]
I don't get your point, other than touchpad not working. Follow instructions about TouchPad in README to make it work.

**Comment by wr-yt** [comment]
Thank you very much for the patch on the touchpad that was updated yesterday. My English is not good. It is translated into English by Google. I am very grateful to my brother.

**Comment by wr-yt** [comment]
In fact, smbios with macbook pro 15,1 is no problem.
