### ISSUE TITLE
After installing VoodooPS2Controller hackintosh crashed.

### ISSUE THREAD

**Issue by zygisjas** [PoomSmart/ASUS-FX504GE-Hackintosh#7]
I have a Asus rog GL503 with very similar specs, after following this guide it worked pretty well. But after installing VoodooPS2Controller kext it restarted suddenly and crashed.

**Comment by PoomSmart** [comment]
Try the latest iteration of this repository.

**Comment by zygisjas** [comment]
> Try the latest iteration of this repository.

Yes, actually it helped. Now it does not have problems with screen backlight or glitches. Thanks
